name: UNP-NMS CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, sqlite, pdo_sqlite

    - name: Install Composer Dependencies
      run: composer install --no-progress --prefer-dist


    - name: Set up SQLite .env
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=:memory:" >> .env
        php artisan key:generate
        php artisan config:clear

    - name: Copy Environment File
      run: cp .env.example .env

    - name: Setup Laravel with SQLite for CI
      run: |
      cp .env.example .env
      echo "DB_CONNECTION=sqlite" >> .env
      echo "DB_DATABASE=:memory:" >> .env
      php artisan key:generate
      php artisan config:clear

    - name: Generate Application Key
      run: php artisan key:generate


    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Unit & Feature Tests
      run: |
      mkdir -p tests/Unit
      php artisan test
     